### ISSUE TITLE
C Comments to Go Comments

### ISSUE THREAD

**Issue by marxriedl** [zimmski/go-clang-phoenix#4]
Transform comments into Go style comments? e.g. what should happen with \param and \returns; there are still a lot of doxygen annotations left

**Comment by zimmski** [comment]
OK since godoc cannot do new lines (WTH?!) the original comments are better suited but need to be adapted.

**Comment by zimmski** [comment]
Well, the comments are not Go idiomatic but at least they are now better readable in the code.
