### ISSUE TITLE
Doxygen defgroups

### ISSUE THREAD

**Issue by marxriedl** [zimmski/go-clang-phoenix#5]
Can we handle doxygen defgroups? Would that make sense for a Go documentation? e.g.
\defgroup CINDEX_CURSOR_TRAVERSAL Traversing the AST with cursors

**Comment by zimmski** [comment]
Nope, it does not. We could use the comments to sort the generation into "grouped files" but then we would rely on heuristics that parse comments. That can fail most of the time.
